version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    versioning-strategy: "increase"
    ignore:
      - dependency-name: "php"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      wordpress-core:
        patterns:
          - "roots/wordpress"
      plugins:
        patterns:
          - "wpackagist-plugin/*"
      themes:
        patterns:
          - "wpackagist-theme/*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "ci"
    commit-message:
      prefix: "ci"
      include: "scope"
